### ISSUE TITLE
Weave is not being closed properly

### ISSUE THREAD

**Issue by leocr03** [zenvia-mobile/docker-komposer#22]
When privateNetwork is enable, Weave containers are up along the services containers. In the down moment, all service containers are closed, but Weave remains up.

This is the stack trace:

Client instance has been closed.
java.lang.IllegalStateException: Client instance has been closed.
    at jersey.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:149)
    at org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:178)
    at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:190)
    at org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:70)
    at com.spotify.docker.client.DefaultDockerClient.resource(DefaultDockerClient.java:1044)
    at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:368)
    at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:362)
    at com.zenvia.komposer.runner.KomposerNetworkSetup.startAdminContainer(KomposerNetworkSetup.groovy:69)
    at com.zenvia.komposer.runner.KomposerNetworkSetup.stop_closure4(KomposerNetworkSetup.groovy:53)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at com.zenvia.komposer.runner.KomposerNetworkSetup.stop(KomposerNetworkSetup.groovy:51)
    at com.zenvia.komposer.runner.KomposerRunner.down(KomposerRunner.groovy:163)
    at com.zenvia.komposer.junit.KomposerRule.after(KomposerRule.groovy:67)
...

**Comment by leocr03** [comment]
Solved in version 1.2.3
